server:
  port: 8083


message: In catalog service
#datasource specific properties
spring:
 application:
  name: product-catalog
 profiles:
    active: prod,dev
 datasource:
    username: root
    password: abcd
    url: jdbc:mysql://localhost:3306/ecommdb
##jpa properties

 jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
  


eureka:
  client:
    service-url:
      default-zone: http://eureka-server